server:
  port: 8080
spring:
  jpa: 
    hibernate: 
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Pentagono
    username: sa
    password: 1234